# Generated by Django 2.0.9 on 2018-11-24 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='experience',
            field=models.CharField(blank=True, choices=[('B', 'Beginner'), ('BI', 'Beginner to Intermediate'), ('I', 'Intermediate'), ('IA', 'Intermediate to Advanced'), ('A', 'Advanced / Professional')], max_length=2, null=True),
        ),
    ]
