# Generated by Django 2.0.9 on 2018-11-29 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20181128_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, height_field='height_field', upload_to='user_directory_path', width_field='width_field'),
        ),
    ]
