# Generated by Django 2.0.9 on 2018-11-30 22:36

from django.db import migrations, models
import lexpy.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_user_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='height_field',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, height_field='height_field', upload_to=lexpy.users.models.user_directory_path, width_field='width_field'),
        ),
        migrations.AlterField(
            model_name='user',
            name='width_field',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
